if minetest.get_modpath("default") then
	register_carpet("default_stone", "default:stone", "Stone Carpet", "default_stone.png", {cracky=3, stone=1})
	register_carpet("default_cobble", "default:cobble", "Cobblestone Carpet", "default_cobble.png", {cracky=3, stone=2})
	register_carpet("default_stonebrick", "default:stonebrick", "Stone Brick Carpet", "default_stone_brick.png", {cracky=2, stone=1})
	register_carpet("default_mossycobble", "default:mossycobble", "Mossy Cobblestone Carpet", "default_mossycobble.png", {cracky=3, stone=1})
	register_carpet("default_desert_stone", "default:desert_stone", "Desert Stone Carpet", "default_desert_stone.png", {cracky=3, stone=1})
	register_carpet("default_desert_cobble", "default:desert_cobble", "Desert Cobblestone Carpet", "default_desert_cobble.png", {cracky=3, stone=2})
	register_carpet("default_desert_stonebrick", "default:desert_stonebrick", "Desert Stone Brick Carpet", "default_desert_stone_brick.png", {cracky=2, stone=1})
	register_carpet("default_sandstone", "default:sandstone", "Sandstone Carpet", "default_sandstone.png", {crumbly=2,cracky=3})
	register_carpet("default_sandstonebrick", "default:sandstonebrick", "Sandstone Brick Carpet", "default_sandstone_brick.png", {cracky=2})
	register_carpet("default_obsidian", "default:obsidian", "Obsidian Carpet", "default_obsidian.png", {cracky=1,level=2})
	register_carpet("default_obsidianbrick", "default:obsidianbrick", "Obsidian Brick Carpet", "default_obsidian_brick.png", {cracky=1,level=2})
	register_carpet("default_dirt", "default:dirt", "Dirt Carpet", "default_dirt.png", {crumbly=3})
	register_carpet("default_sand", "default:sand", "Sand Carpet", "default_sand.png", {crumbly=3, sand=1})
	register_carpet("default_desert_sand", "default:desert_sand", "Desert Sand Carpet", "default_desert_sand.png", {crumbly=3})
	register_carpet("default_gravel", "default:gravel", "Gravel Carpet", "default_gravel.png", {crumbly=2})
	register_carpet("default_clay", "default:clay", "Clay Carpet", "default_clay.png", {crumbly=3})
	register_carpet("default_snow", "default:snow", "Snow Carpet", "default_snow.png", {crumbly=3})
	register_carpet("default_ice", "default:ice", "Ice Carpet", "default_ice.png", {cracky=3})
	register_carpet("default_tree", "default:tree", "Tree Carpet", "default_tree_top.png", {tree=1,choppy=2,oddly_breakable_by_hand=1,flammable=2})
	register_carpet("default_wood", "default:wood", "Wood Carpet", "default_wood.png", {choppy=2,oddly_breakable_by_hand=2,flammable=3,wood=1})
	register_carpet("default_leaves", "default:leaves", "Leaves Carpet", "default_leaves.png", {snappy=3, flammable=2, leaves=1})
	register_carpet("default_jungletree", "default:jungletree", "Jungle Tree Carpet", "default_jungletree_top.png", {tree=1,choppy=2,oddly_breakable_by_hand=1,flammable=2})
	register_carpet("default_junglewood", "default:junglewood", "Junglewood Carpet", "default_junglewood.png", {choppy=2,oddly_breakable_by_hand=2,flammable=3,wood=1})
	register_carpet("default_jungleleaves", "default:jungleleaves", "Jungle Leaves Carpet", "default_jungleleaves.png", {snappy=3, flammable=2, leaves=1})
	register_carpet("default_pinetree", "default:pinetree", "Pine Tree Carpet", "default_pinetree_top.png", {tree=1,choppy=2,oddly_breakable_by_hand=1,flammable=2})
	register_carpet("default_pinewood", "default:pinewood", "Pinewood Carpet", "default_pinewood.png", {choppy=2,oddly_breakable_by_hand=2,flammable=3,wood=1})
	register_carpet("default_pine_needles", "default:pine_needles", "Pine Needles Carpet", "default_pine_needles.png", {snappy=3, flammable=2, leaves=1})
	register_carpet("default_coalblock", "default:coalblock", "Coal Carpet", "default_coal_block.png", {cracky=3})
	register_carpet("default_steelblock", "default:steelblock", "Steel Carpet", "default_coal_block.png", {cracky=1,level=2})
	register_carpet("default_copperblock", "default:copperblock", "Copper Carpet", "default_copper_block.png", {cracky=1,level=2})
	register_carpet("default_bronzeblock", "default:bronzeblock", "Bronze Carpet", "default_bronze_block.png", {cracky=1,level=2})
	register_carpet("default_mese", "default:mese", "Mese Carpet", "default_mese_block.png", {cracky=1,level=2})
	register_carpet("default_goldblock", "default:goldblock", "Gold Carpet", "default_gold_block.png", {cracky=1})
	register_carpet("default_diamondblock", "default:diamondblock", "Diamond Carpet", "default_diamond_block.png", {cracky=1,level=3})
	register_carpet("default_glass", "default:glass", "Glass Carpet", "default_glass.png", {cracky=3,oddly_breakable_by_hand=3})
	register_carpet("default_obsidian_glass", "default:obsidian_glass", "Obsidian Glass Carpet", "default_obsidian_glass.png", {cracky=3,oddly_breakable_by_hand=3})
	register_carpet("default_nyancat", "default:nyancat", "Nyan Cat Carpet", "default_nc_front.png", {cracky=2})
	register_carpet("default_nyancat_rainbow", "default:nyancat_rainbow", "Rainbow Carpet", "default_nc_rb.png", {cracky=2})
end
